const CACHE_PREFIX='purple-gestao-';
const CACHE='purple-gestao-v153';
const ASSETS=['./','./index.html','./styles.css?v=80','./auth/config.js?v=42','./assets/vendor/supabase-js-2.min.js','./core/supabase-service.js?v=3','./core/permissions-service.js?v=1','./core/system-status.js?v=1','./core/ui-service.js?v=1','./auth/bootstrap.js?v=11','./app.js?v=152','./manifest.webmanifest','./assets/brand/purple-gestao-light.png','./assets/brand/purple-gestao-dark.png','./assets/brand/purple-gestao-symbol.png','./assets/brand/icon-purple-gestao-192.png','./assets/brand/icon-purple-gestao-512.png','./assets/brand/apple-touch-icon.png','./assets/brand/favicon.ico'];
const CRITICAL=/\/(?:index\.html|app\.js|styles\.css|auth\/config\.js|auth\/bootstrap\.js|core\/.*\.js)(?:\?|$)/;
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
async function networkFirst(request){const cache=await caches.open(CACHE);try{const response=await fetch(request,{cache:'no-store'});if(response&&response.ok)cache.put(request,response.clone());return response}catch(error){return await cache.match(request)||await caches.match('./index.html')}}
async function cacheFirst(request){const cached=await caches.match(request);if(cached)return cached;const response=await fetch(request);if(response&&response.ok)(await caches.open(CACHE)).put(request,response.clone());return response}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;if(event.request.mode==='navigate'||CRITICAL.test(url.pathname))event.respondWith(networkFirst(event.request));else event.respondWith(cacheFirst(event.request))});
