const assert=require('node:assert');
const fs=require('node:fs');

const app=fs.readFileSync('app.js','utf8');
const afterOverride=app.slice(app.lastIndexOf('Override autoritativo final'));

assert(app.includes("if(tab==='payments')return studentPaymentsContentFull(s)"), 'A aba Financeiro do aluno deve renderizar a central financeira nova.');
assert(afterOverride.includes('Registrar pagamento anterior'), 'A central deve permitir registrar pagamento anterior.');
assert(afterOverride.includes('Valor integral'), 'A central deve mostrar valor integral.');
assert(afterOverride.includes('Valor com pontualidade/desconto'), 'O modal deve ter valor com desconto/pontualidade.');
assert(afterOverride.includes('Total de parcelas'), 'O modal deve permitir parcelas.');
assert(afterOverride.includes('PIX + Boleto'), 'O modal deve oferecer uma cobrança única Asaas com PIX + boleto.');
assert(afterOverride.includes('Carnê digital'), 'A central do aluno deve permitir abrir o carnê digital.');
assert(afterOverride.includes('Excluir definitivamente'), 'A confirmação deve deixar claro que a exclusão é definitiva.');
assert(afterOverride.includes('Excluir parcela'), 'A ação principal do menu deve continuar como Excluir parcela.');
assert(!afterOverride.includes('Cancelar cobrança Asaas'), 'A UI final não deve expor opção de cancelamento separada.');
assert(!afterOverride.includes('Canceladas <b>'), 'A UI final não deve ter subaba de parcelas canceladas.');
assert(afterOverride.includes('studentFinancialBulkBar'), 'A tela do aluno deve ter barra para ações em lote no financeiro.');
assert(afterOverride.includes('toggleStudentFinancialSelection'), 'A tela deve permitir selecionar mais de uma parcela.');
assert(app.includes('data-financial-select-toggle'), 'Seleção de parcela deve usar botão real com delegação de clique.');
assert(afterOverride.includes('data-financial-row-selectable'), 'O card da parcela também deve permitir clique para seleção.');
assert(afterOverride.includes("return financialStatusFor(item)!=='paid'"), 'Toda parcela não paga deve poder ser selecionada para exclusão.');
assert(!afterOverride.includes('type="checkbox" ${checked'), 'Seleção final não deve depender de checkbox invisível dentro do card.');
assert(afterOverride.includes('Excluir selecionadas'), 'A tela deve permitir excluir parcelas selecionadas em lote.');
assert(afterOverride.includes('confirmArchiveSelectedFinancialRows'), 'Exclusão em lote deve passar por confirmação segura.');
assert(afterOverride.includes('removida definitivamente'), 'A exclusão em lote deve remover de vez, sem arquivar.');
assert(afterOverride.includes('Copiar código'), 'O menu ⋯ deve permitir copiar o código da cobrança.');
assert(afterOverride.includes('Gerar cobrança Asaas'), 'O menu ⋯ deve permitir gerar cobrança Asaas para parcela manual.');
assert(afterOverride.includes("action==='copyPix'"), 'O menu ⋯ deve ligar a ação de copiar PIX.');
assert(afterOverride.includes("action==='openBoleto'"), 'O menu ⋯ deve ligar a ação de abrir boleto.');
assert(afterOverride.includes('financialIsAsaas'), 'O menu ⋯ deve reconhecer cobranças Asaas mesmo com origem incompleta.');
assert(afterOverride.includes("action==='copyCode'"), 'A ação copyCode deve estar ligada ao menu financeiro.');
assert(afterOverride.includes('student-financial-popover'), 'O menu ⋯ deve ser popover ancorado e não depender de <details>.');
assert(afterOverride.includes('data-financial-menu-trigger'), 'O menu ⋯ deve usar delegação por data attributes.');
assert(afterOverride.includes("document.addEventListener('click'"), 'O menu ⋯ deve sobreviver a re-render por delegação global.');
assert(afterOverride.includes("document.addEventListener('keydown'"), 'O menu ⋯ deve fechar com Escape.');
assert(!afterOverride.includes('<h3>Configuração financeira</h3>'), 'A versão final compacta não deve renderizar o card Configuração financeira.');
assert(!afterOverride.includes('<h3>Resumo operacional</h3>'), 'A versão final compacta não deve renderizar o card Resumo operacional.');
assert(afterOverride.includes('brl-input-wrap'), 'Campos monetários devem usar wrapper BRL com prefixo fora do valor.');
assert(afterOverride.includes('parseBRLInput'), 'Deve existir helper central para parse BRL.');
assert(afterOverride.includes('formatBRL'), 'Deve existir helper central para format BRL.');
assert(afterOverride.includes('financialDescriptionFromParts'), 'Descrição automática por tipo/competência/parcela deve existir.');
assert(afterOverride.includes('financialCompetenceFromDue'), 'Competência automática a partir do vencimento deve existir.');
assert(afterOverride.includes('openStudentFinancialPayment'), 'Registro de pagamento manual contextual deve existir.');
assert(afterOverride.includes('financialFullValue'), 'O salvamento deve ler valor integral.');
assert(afterOverride.includes('financialPunctualValue'), 'O salvamento deve ler valor pontual.');
assert(afterOverride.includes('financialStableIdempotencyKey'), 'Criação em lote deve usar chave de idempotência estável por parcela.');
assert(afterOverride.includes('openStudentFinancialBooklet'), 'Carnê digital deve estar exportado para a UI.');

console.log('financial UI binding test ok');
