const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('app.js','utf8');
let cache={},loads=0,releaseRead,releaseWrite,fail=false,saved=[],messages=[];
const user={id:'anna',role:'leader'},workspace={version:'manual-empty-v2',routines:[],events:[],filters:{view:'team'}};
const ctx=vm.createContext({console,Date,Map,Promise,JSON,State:{user,page:'twr',db:{settings:{},twr:workspace}},document:{hidden:false,body:{classList:{contains:()=>false}}},window:{},canPersistRemotely:()=>true,twrCanManage:()=>true,twrCanViewTeam:()=>true,cloneValue:value=>JSON.parse(JSON.stringify(value)),uid:()=>String(Math.random()),readLocalCatalogCache:()=>cache,writeLocalCatalogCache:patch=>{cache={...cache,...patch}},writeLocalTwrCache(){},renderPage(){},toast:message=>messages.push(message),resolveTeacherIdForUser:()=>'',saveLocalSessionCache(){},saveAppRecord:async row=>{if(fail)throw new Error('RLS denied');if(releaseWrite===true)await new Promise(resolve=>{releaseWrite=resolve});saved.push(row)}});
vm.runInContext(source.slice(source.indexOf('const Storage={'),source.indexOf('function storedSidebarMode()')),ctx);
vm.runInContext('globalThis.storage=Storage',ctx);
vm.runInContext(source.slice(source.indexOf('const TeacherAcademicSync='),source.indexOf('function bindTeacherAcademicSync(){')),ctx);
vm.runInContext(source.slice(source.indexOf("function twrSaveAndRender(message='')"),source.indexOf('function twrValidOn(')),ctx);
const tick=()=>new Promise(setImmediate);
(async()=>{
  ctx.storage.load=async()=>{loads++;return new Promise(resolve=>{releaseRead=resolve})};
  ctx.storage.save=()=>{throw new Error('Must not save unrelated modules')};
  const read=ctx.refreshTeacherAcademicData({force:true});await tick();
  workspace.events.push({id:'replacement',teacherId:'erica',type:'REPOSICAO'});
  await ctx.twrSaveAndRender('Salvo');await tick();
  releaseRead({user,db:{settings:{},twr:{events:[]}},baseline:new Map([['stale','old']]),metadata:new Map()});await read;
  assert.equal(ctx.State.db.twr.events[0].id,'replacement','A read started before the edit cannot erase the new activity');
  assert(!ctx.storage.baseline.has('stale'),'Discarded read cannot replace the write baseline');
  assert.equal(saved.length,1);assert.equal(saved[0].kind,'twr_workspace');assert.equal(saved[0].data.events[0].id,'replacement');
  assert.equal(cache.pendingTwr,null);
  releaseWrite=true;
  const write=ctx.twrSaveAndRender('Salvo');await tick();
  const beforeLoads=loads;await ctx.refreshTeacherAcademicData({force:true});assert.equal(loads,beforeLoads,'Do not refresh during a pending write');
  workspace.events.push({id:'later-edit'});
  releaseWrite();await write;await tick();
  assert.equal(saved.at(-1).data.events.length,1,'Queued write uses an immutable snapshot');
  fail=true;
  await assert.rejects(ctx.twrSaveAndRender('Salvo'),/RLS denied/);await tick();
  assert.equal(ctx.storage.twrFailed,true);assert.equal(cache.pendingTwr.workspace.events.length,2,'Failed records remain recoverable locally');
  await ctx.refreshTeacherAcademicData({force:true});assert.equal(loads,beforeLoads,'Failed records cannot be replaced by a remote refresh');
  assert(ctx.twrSyncBanner().includes('Tentar salvar novamente'));
  fail=false;releaseWrite=false;await ctx.retryTwrSync();await tick();
  assert.equal(ctx.storage.twrFailed,false);assert.equal(cache.pendingTwr,null);assert.equal(saved.at(-1).data.events.length,2);
  assert(messages.some(message=>message.includes('Confirmado no banco')));
  assert(source.includes('async load({applyBaseline=true}={})'));
  assert(source.includes('pendingTwr?.userId===normalizedUser.id'),'Failed cache is restored only for its own authenticated user');
  console.log('PASS: stale refresh rejected, isolated TWR writes, immutable snapshots, failure preservation and confirmed retry.');
})().catch(error=>{console.error(error);process.exitCode=1});
