(function(){
  'use strict';
  const CONFIG=window.PurpleAuthConfig||{};
  const AUTH_EMAIL_ALIASES=Object.freeze({
    'direcao@purple.com':'direcao@purple.com.br',
    'pedagogico@purple.com':'pedagogico@purple.com.br',
    'financeiro@purple.com':'financeiro@purple.com.br',
    'retencao@purple.com':'retencao@purple.com.br'
  });
  const bootstrap={recovery:false,failedStep:null,errors:[],loginState:'booting',client:null,loadedScripts:[...document.scripts].map(script=>script.getAttribute('src')||'[inline]')};
  const readError=error=>error instanceof Error?`${error.name}: ${error.message}`:String(error);
  const friendlyError=(error)=>typeof window.friendlyError==='function'?window.friendlyError(error,'login'):'Não foi possível concluir a operação. Tente novamente.';
  const syncBootstrap=()=>{window.PurpleAuthBootstrap=bootstrap; if(window.PurpleBootstrap)Object.assign(window.PurpleBootstrap,bootstrap);};
  const record=(step,error)=>{const message=readError(error);bootstrap.errors.push({step,message,at:new Date().toISOString()});console.error(`Purple Gestão auth [${step}]`,error);syncBootstrap();return message};
  const enterRecoveryMode=(step,error)=>{bootstrap.recovery=true;bootstrap.failedStep=step;bootstrap.loginState='recovery';record(step,error);renderRecoveryNotice();syncBootstrap()};
  const ensureAppStub=()=>{window.App=window.App||{};window.App.login=window.App.login||((...args)=>login(...args));window.App.logout=window.App.logout||((...args)=>logout(...args));window.App.showDiagnostics=window.App.showDiagnostics||(()=>showDiagnostics());window.App.fillLogin=window.App.fillLogin||((email)=>fillLogin(email));window.App.closeModal=window.App.closeModal||(()=>{});};
  const hasClient=()=>!!(bootstrap.client&&bootstrap.client.auth&&typeof bootstrap.client.from==='function');
  const validateSdk=()=>{bootstrap.sdkType=typeof window.supabase;if(typeof window.supabase!=='object')throw new Error('window.supabase não está disponível.');if(typeof window.supabase.createClient!=='function')throw new Error('window.supabase.createClient não é uma função.');if(!CONFIG.supabaseUrl)throw new Error('SUPABASE_URL não configurada.');if(!CONFIG.supabaseKey)throw new Error('SUPABASE_KEY não configurada.')};
  const createClient=()=>{if(hasClient())return bootstrap.client;validateSdk();bootstrap.client=window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage,storageKey:'purple-gestao-auth'}});if(!bootstrap.client||!bootstrap.client.auth||typeof bootstrap.client.from!=='function')throw new Error('Cliente Supabase inválido após createClient().');bootstrap.loginState='ready';console.info('Purple Gestão auth [supabase] cliente inicializado.');syncBootstrap();return bootstrap.client};
  const safeState=()=>window.PurpleState||null;
  const safeStorage=()=>window.PurpleStorage||null;
  const normalizeAuthEmail=value=>{const email=String(value||'').trim().toLowerCase();return AUTH_EMAIL_ALIASES[email]||email};
  const fillLogin=email=>{const emailEl=document.getElementById('loginEmail');const passEl=document.getElementById('loginPassword');if(emailEl)emailEl.value=email;if(passEl)passEl.value='123456'};
  const renderRecoveryNotice=()=>{const card=document.querySelector('.login-card');if(!card)return;let box=document.getElementById('recoveryModeBox');if(!bootstrap.recovery){box?.remove();return}if(!box){box=document.createElement('div');box.id='recoveryModeBox';box.className='demo-accounts';const restricted=document.querySelector('.login-restricted');(restricted?.parentNode||card).insertBefore(box,restricted||null)}const latest=bootstrap.errors.at(-1);box.innerHTML=`<b>Recovery Mode ativo</b><p style="margin:8px 0 10px">A inicialização entrou em modo degradado. Etapa com falha: <b>${String(bootstrap.failedStep||'bootstrap')}</b>.</p><p style="margin:0 0 12px">${String(latest?.message||'Sem detalhes adicionais.')}</p><div class="section-actions" style="justify-content:flex-start"><button type="button" class="btn soft small" onclick="App.showDiagnostics()">Abrir diagnóstico</button><button type="button" class="btn ghost small" onclick="App.fillLogin('direcao@purple.com')">Usar login local</button></div>`};
  const diagnosticsPayload=()=>({appVersion:CONFIG.appVersion||'unknown',serviceWorkerVersion:CONFIG.serviceWorkerVersion||'unknown',manifestVersion:CONFIG.manifestVersion||'manifest.webmanifest',bootstrapErrors:[...bootstrap.errors],loadedScripts:[...bootstrap.loadedScripts],loadedResources:typeof performance!=='undefined'&&performance?.getEntriesByType?performance.getEntriesByType('resource').map(entry=>entry.name):[],supabase:{sdkType:typeof window.supabase,createClientType:typeof window.supabase?.createClient,url:CONFIG.supabaseUrl,keyConfigured:Boolean(CONFIG.supabaseKey),clientCreated:hasClient()},app:{exists:typeof window.App,loginType:typeof window.App?.login,recovery:bootstrap.recovery},loginState:{state:bootstrap.loginState,user:safeState()?.user?{id:safeState().user.id,email:safeState().user.email,role:safeState().user.role}:null}});
  const showDiagnostics=()=>{const payload=diagnosticsPayload();console.info('Purple Gestão diagnostics',payload);if(document.getElementById('modalRoot')&&typeof window.modal==='function')window.modal(`<div class="modal-head"><div><span class="eyebrow">Diagnóstico</span><h3>Purple Gestão Recovery Mode</h3></div><button class="modal-close" onclick="App.closeModal()">×</button></div><pre style="white-space:pre-wrap;max-height:60vh;overflow:auto;font-size:12px;line-height:1.5;background:#f8f5fb;border:1px solid var(--line);border-radius:16px;padding:16px">${String(JSON.stringify(payload,null,2)).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}</pre><div class="section-actions"><button class="btn ghost" onclick="App.closeModal()">Fechar</button></div>`,true);return payload};
  const restoreSession=async()=>{if(!hasClient())throw new Error('Supabase indisponível para restauração de sessão.');const storage=safeStorage();const state=safeState();if(!storage||!state)throw new Error('Estado da aplicação indisponível para restauração de sessão.');const loaded=await storage.load();if(!loaded.user.active)throw new Error('Usuário inativo');state.user=loaded.user;state.db=loaded.db;state.sector=state.user.accessScope==='all_sectors'?'integrado':state.user.sector;bootstrap.loginState='session-loaded';await window.syncAutomaticTasks?.();await window.unlockAchievements?.();window.startApp?.()};
  const diagnosticLocalLogin=async(email,password)=>{const state=safeState();if(typeof window.defaultDB!=='function'||typeof window.normalizeDiagnosticEmail!=='function'||typeof window.createLocalDiagnosticUser!=='function')throw new Error('Login local de diagnóstico indisponível.');const normalized=window.normalizeDiagnosticEmail(email),db=window.defaultDB(),user=db.users.find(item=>item.email===normalized||item.email===email.trim().toLowerCase());if(!user||user.password!==password)throw new Error('Login local de diagnóstico inválido. Use uma conta demonstrativa conhecida.');if(!state)throw new Error('Estado da aplicação indisponível.');state.db=db;state.user=window.createLocalDiagnosticUser(user,email.trim().toLowerCase());state.sector=state.user.accessScope==='all_sectors'?'integrado':state.user.sector;bootstrap.loginState='local-diagnostic';window.startApp?.();window.toast?.('Recovery Mode ativo com login local de diagnóstico.')};
  const login=async(emailArg,passwordArg)=>{const email=normalizeAuthEmail(emailArg ?? document.getElementById('loginEmail')?.value ?? '');const password=passwordArg ?? document.getElementById('loginPassword')?.value ?? '';const errorBox=document.getElementById('loginError');const button=document.querySelector('.login-card button[type="submit"]');if(errorBox)errorBox.classList.add('hidden');if(button){button.disabled=true;button.classList.add('loading')}try{if(!hasClient()){await diagnosticLocalLogin(email,password);return}bootstrap.loginState='authenticating';const {error}=await bootstrap.client.auth.signInWithPassword({email,password});if(error)throw error;bootstrap.loginState='authenticated';await restoreSession();await bootstrap.client.from('profiles').update({last_login_at:new Date().toISOString()}).eq('id',safeState().user.id);safeState().user.lastLoginAt=new Date().toISOString();window.logAudit?.('Login','Acesso ao Purple Gestão')}catch(error){bootstrap.loginState='login-error';if(errorBox){errorBox.textContent=bootstrap.recovery?`${friendlyError(error)} Falha atual: ${bootstrap.failedStep||'bootstrap'}.`:friendlyError(error);errorBox.classList.remove('hidden')}if(hasClient())await bootstrap.client.auth.signOut().catch(signOutError=>console.warn('Purple Gestão auth [signOut]',signOutError))}finally{if(button){button.disabled=false;button.classList.remove('loading')}}};
  const logout=async()=>{const state=safeState();if(state?.user)window.logAudit?.('Logout','Saída do Purple Gestão');if(safeStorage()?.pending)await safeStorage().pending;if(hasClient())await bootstrap.client.auth.signOut().catch(error=>console.warn('Purple Gestão auth [logout]',error));bootstrap.loginState='logged-out';if(state)state.user=null;document.getElementById('appShell')?.classList.add('hidden');document.getElementById('loginScreen')?.classList.remove('hidden');renderRecoveryNotice()};
  const init=()=>{try{createClient()}catch(error){bootstrap.client=null;bootstrap.loginState='recovery';enterRecoveryMode('inicialização do Supabase',error)}finally{syncBootstrap();ensureAppStub();window.AppDiagnostics=showDiagnostics}};
  syncBootstrap();ensureAppStub();window.AppDiagnostics=showDiagnostics;window.PurpleAuth={config:CONFIG,state:bootstrap,init,createClient,hasClient,login,logout,restoreSession,showDiagnostics,fillLogin,enterRecoveryMode,diagnosticsPayload};window.App=window.App||{};window.App.login=window.App.login||((...args)=>login(...args));window.App.logout=window.App.logout||((...args)=>logout(...args));window.App.showDiagnostics=window.App.showDiagnostics||showDiagnostics;window.App.fillLogin=window.App.fillLogin||fillLogin;window.App.closeModal=window.App.closeModal||(()=>{});init();
})();
